name: Python CI

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Run tests
      run: |
          python -m pip install --upgrade pip
          pip install pytest
          pytest exercise_2
    - name: Set test color
      run: |
        if [ $? -eq 1 ]; then
          echo "badge_color==green" >> $GITHUB_ENV
        else
          echo "badge_color==red" >> $GITHUB_ENV
    - name: Badge updater
      uses: ./.github/actions/change-badge
      with:
        badge_color: ${{ env.badge_color }}


  lint:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Linting
      run: |
          python -m pip install --upgrade pip
          pip install flake8
          flake8 exercise_2
    - name: Set lint color
      run: |
        if [ $? -eq 1 ]; then
          echo "badge_color==green" >> $GITHUB_ENV
        else
          echo "badge_color==red" >> $GITHUB_ENV
    - name: Badge updater
      uses: ./.github/actions/change-badge
      with:
        badge_color: ${{ env.badge_color }}

  badge:
    needs: ['test','lint']
    runs-on: ubuntu-latest
    steps:
    - name: Set final color
      run: |
        if [ $? -eq 1 ]; then
          echo "badge_color==green" >> $GITHUB_ENV
        else
          echo "badge_color==red" >> $GITHUB_ENV
    - name: Badge updater
      uses: ./.github/actions/change-badge
      with:
        badge_color: ${{ env.badge_color }}

    



    

