name: Custom workflow

on:
  push:
  schedule:
    - cron: "*/5 * * * *"


jobs:
  custom-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4
      - name: Greeting
        uses: ./.github/actions/my-action
        with:
          custom_param: "Georgi"

