name: Protected envs and stages

on:
  push:
    branches:
      - master


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Build or simulate building
        run: |
          echo "Building..."
          sleep 5

      - name: Finish building
        run: echo "Build completed successfully"

  deploy-to-envs:
    needs: build-and-push
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        environment: ["dev", "acc", "pro"]
      max-parallel: 1
    environment: ${{ matrix.environment }}
    steps:
      - name: Deploy task
        run: echo "Deploying to ${{ matrix.environment }}"
